// <auto-generated />
using System;
using MicroserviceC.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroserviceC.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518170000_AddKnowledgeArticles")]
    partial class AddKnowledgeArticles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroserviceC.API.Models.Entities.DamageCatalog", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("AttentionLevel").HasColumnType("int");
                    b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("DamageCatalog", (string)null);
                });

            modelBuilder.Entity("MicroserviceC.API.Models.Entities.ServiceCatalog", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("AttentionLevel").HasColumnType("int");
                    b.Property<string>("Category").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("DamageCatalogId").HasColumnType("int");
                    b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("DamageCatalogId");
                    b.ToTable("ServiceCatalog", (string)null);
                });

            modelBuilder.Entity("MicroserviceC.API.Models.Entities.KnowledgeArticle", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Cause").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Category").IsRequired().HasColumnType("nvarchar(450)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("CreatedByName").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("CreatedByUserId").HasColumnType("int");
                    b.Property<string>("Problem").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Solution").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Symptoms").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("TicketId").HasColumnType("int");
                    b.Property<string>("TicketNumber").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2");
                    b.Property<int>("ViewCount").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("Category");
                    b.HasIndex("TicketId");
                    b.ToTable("KnowledgeArticles", (string)null);
                });

            modelBuilder.Entity("MicroserviceC.API.Models.Entities.ServiceCatalog", b =>
                {
                    b.HasOne("MicroserviceC.API.Models.Entities.DamageCatalog", "DamageCatalog")
                        .WithMany("Services")
                        .HasForeignKey("DamageCatalogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("DamageCatalog");
                });

            modelBuilder.Entity("MicroserviceC.API.Models.Entities.DamageCatalog", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
